### ISSUE TITLE
Warning in Keil uVision 5

### ISSUE THREAD

**Issue by Bobthehunter** [tobbad/nfc05_uart_reader_c#1]
Hello,

I'm using this project in Keil uVision 5 and when I build the files of the project I get an error in the file "platform.h" saying that "warning: #47-D: incompatible redefinition of macro "USE LOGGER"" @ "#define USE_LOGGER LOGGER_ON".

Can you help me with this issue?

Regards,
Bob

**Comment by tobbad** [comment]
I developed the code out of existing STM projects for the NFC reader for ARM GNU GCC. So I have no KEIL Knowledge and can not help you. Further this project is Work in progress and not yet working as it should do.

Maybe it would be better to use the existing KEIL project in the official STM code (See readme) as starting point for your solution.
